### ISSUE TITLE
frontend (basics_macos_latest) is flaky

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/examples#399] opened 2024-01-17 10:17 UTC
See https://buildkite.com/bazel/bazel-bazel-examples/builds/2538#018d16e9-cb64-4bd3-b317-c100685c2667

```
(11:03:10) ERROR: /Users/buildkite/builds/bk-imacpro-5/bazel/bazel-bazel-examples/frontend/BUILD.bazel:10:22: Copying directory aspect_rules_js~1.34.1~npm~npm__next__13.0.5__-1955910335/package failed: Exec failed due to IOException: /private/var/tmp/_bazel_buildkite/32e4ba4d0650606d694d288e11046927/execroot/_main/external/aspect_rules_js~1.34.1~npm~npm__next__13.0.5__-1955910335/package (No such file or directory)
(11:03:11) INFO: Elapsed time: 26.960s, Critic
```

/cc @alexeagle

**Comment by alexeagle** [comment] 2024-02-28 22:40
Yes, this is a known issue. I just added to our FAQ https://github.com/aspect-build/rules_js/blob/main/docs/faq.md#flaky-build-failure-exec-failed-due-to-ioexception
Actually we have had quite a bit of back-and-forth about how to make our copy rules work properly with remote execution.

**Comment by alexeagle** [comment] 2024-04-22 14:48
Dupe of #421

**Closed by alexeagle** 2024-04-22 14:48 UTC
