### ISSUE TITLE
java examples error

### ISSUE THREAD

**Issue by miramar-labs** [bazelbuild/examples#86] opened 2019-01-29 04:41 UTC
when importing examples/java-tutorial into Intellij 2018.3 (using latest Bazel plugin) I see the following error:

Error:(1, 1) no such target '//:greeter': target 'greeter' not declared in package '' defined by /Users/aaron/bazel/examples/java-tutorial/BUILD and referenced by '//src/main/java/com/example/cmdline:runner'.

**Comment by mihaigalos** [comment] 2019-02-05 09:39
reproducible with Bazel 0.22.0 on Ubuntu 18.04 *only* when running `bazel build  //...`. Building with `bazel build //:ProjectRunner` works. 

I still do not understand why there is a `ProjectRunner.java` and a `Runner.java`, both implementing `main()`.. It looks like these are two different examples.

**Comment by trironkk** [comment] 2019-02-19 05:31
Ran into this, too.

https://github.com/bazelbuild/examples/pull/84 should correct it - maybe @lberki could review?

**Comment by fweikert** [comment] 2019-02-26 16:18
+1 - I'm in the process of setting up a Buildkite presubmit for the examples repo, but ran into the same errors.

**Comment by jin** [comment] 2019-02-26 17:18
I can no longer reproduce this. The errors in presubmit are not related to this and will be fixed by https://github.com/bazelbuild/examples/pull/97

**Closed by jin** 2019-02-26 17:18 UTC
